language: php
php:
  - '7.1'
  - '7.2'
  -
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --ignore-platform-reqs --dev

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php